---
# common/handlers/main.yml

- name: update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  ignore_errors: yes

- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes
  ignore_errors: yes

- name: restart firewall
  command: /etc/network/if-down.d/iptables_save && /etc/network/if-pre-up.d/iptables

- name: start firewall
  command: /etc/network/if-pre-up.d/iptables

- name: harden IP stack
  command: /usr/sbin/service procps start

- name: restart postfix
  service: name=postfix state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload upstart config
  command: /sbin/initctl reload-configuration

- name: restart monit
  service: name=monit state=restarted

- name: start monit
  service: name=monit state=started
